### ISSUE TITLE
Question: on the estimation of a probability for predicted value

### ISSUE THREAD

**Issue by ivan-marroquin** [CDonnerer/xgboost-distribution#44]
Hi,

Many thanks for bringing together XGBoost and NGBoost!

I am interested in estimating a probability for predicted value when using a regressor model. So, I would like to have your opinion if my approach makes sense. 

First, I train the XGBDistribution with a normal distribution. Then, I get the "loc" and "scale" parameters of the distribution on a predicted sample. And finally, I compute the CDF as follows:

estimated_probability= norm.cdf(predicted value, loc of predicted value, scale of predicted value) - norm.cdf(predicted value - (predicted_value * 0.10), loc of predicted value, scale of predicted value)

Thanks for your help,

Ivan

**Comment by CDonnerer** [comment]
Hi @ivan-marroquin ,
I don't think this fully makes sense: XGBDistribution only predicts the parameters of a given distribution, but does not provide point distributions like "normal" regressors. You could of course compute (e.g.) the mean from the parameters to get a point estimate, which would (by definition) evaluate to the same CDF.
The above could work if you have some hold out data with labels, which is then similar to using an `eval_set` during training.
Hope this helps!

**Comment by ivan-marroquin** [comment]
Hi @CDonnerer 

Thanks for your comments. I found this publication: https://cyberleninka.org/article/n/499637/viewer

which seems to show that it is possible to compute the probability of a predicted value by using CDF computed based on the lower and upper interval. 

I would like to know your opinion,

Kind regards,

Ivan

**Comment by StatMixedML** [comment]
@ivan-marroquin You might want to check out XGBoostLSS that allows to draw random samples from the predicted distribution + quantiles, which is what you asked for

https://github.com/StatMixedML

**Comment by ivan-marroquin** [comment]
Hi @StatMixedML 

Many thanks for the suggestion!

Ivan
