### ISSUE TITLE
Verbal mode?

### ISSUE THREAD

**Issue by thomasaarholt** [CDonnerer/xgboost-distribution#48]
At the moment xgboost-dist is silent until it suddenly spits out the result. Is there a way to make it print losses during the optimization process?

**Comment by CDonnerer** [comment]
Hi @thomasaarholt ,
Yes, there is! When fitting the model, please use the `verbose=True` kwarg. e.g.
```
model.fit(
    X_train, y_train, 
    eval_set=[(X_test, y_test)], 
    early_stopping_rounds=10, 
    verbose=True
)
```

Note that this will only work if you provide an eval set, see also the [docs](https://xgboost-distribution.readthedocs.io/en/latest/api/xgboost_distribution.XGBDistribution.html#xgboost_distribution.XGBDistribution.fit) for more info.

**Comment by thomasaarholt** [comment]
Hahaha, I feel the fool! Could have sworn that I looked before asking! Thanks!
