### ISSUE TITLE
Question on evaluation metric choices and meaning

### ISSUE THREAD

**Issue by ShiyangTey** [CDonnerer/xgboost-distribution#63]
Hi Christian,

I have a shallow background on ML and Data Science, and I have a noob question.

When I evaluate my model, I could not choose evaluation metrics, as there's only a default 'NormalError'.
May I know what does NormalError means? Is the the same as Standard Error, SE = Std.d/ sqrt(n)?

Thank you.

**Comment by CDonnerer** [comment]
Hi,
Thanks for raising.
This is indeed not a very helpful message, I've updated this to print `Normal-NLL` and so on for other distributions. Here, `NLL` is the negative log likelihood of a given distribution. Meaning that, for a given feature vector X, we aim to find the parameters of the distribution (for a normal distribution the mean and std) which best fit the target y, i.e. which minimises the negative log likelihood. This is currently the only supported loss for the distributions.
Hope this helps!
