### ISSUE TITLE
random_state not working?

### ISSUE THREAD

**Issue by htian97** [CDonnerer/xgboost-distribution#71]
I tried to set different random_state but all models are giving the same prediction results.

**Comment by CDonnerer** [comment]
You should get the same behaviour as for an `XGBRegressor`, however you need to use some sort of sub sampling for this to take effect, otherwise the behaviour is deterministic. See (e.g.) here [https://stackoverflow.com/a/50797842](https://stackoverflow.com/a/50797842)
